# This workflow will test the build system, then build the extension and upload an artifact
name: Test build system and upload extension

on:
  push:
    # only trigger on branches, not on tags
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: make gettext gnome-shell
        version: 1.0

    - name: Test extension builds from scratch
      run: |
        make build

    - uses: actions/upload-artifact@v4
      with:
        name: ollama-tray@fxgsell.github.com.zip
        path: ollama-tray@fxgsell.github.com.zip